name: flutter_application_4
description: Aplicativo de agendamento de chácara com recursos avançados.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.9.0
  flutter_local_notifications: ^17.1.0
  url_launcher: ^6.3.0
  fl_chart: ^0.68.0
  dropdown_search: ^5.0.6
  http: ^1.2.0
  intl: ^0.19.0
  provider: ^6.1.5
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
